### ISSUE TITLE
l10n_fr_siret installation will remove existing siret

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/l10n-france#102]
In case that you have an existing db, and you install the module.
The module replace the existing siret with a computed field without any value inside.
We need to do a pre/post migration script

**Comment by legalsylvain** [comment]
Hi @sebastienbeau. I'm not sure that the field will be recomputed, if it exist in the database. It's a technic of Openupgrade to speed up migration for computed field : we are generally creating the field before, and populating it with SQL script. So I'm not sure about what you're saying. Did you tested ? 

In the other side, since V11, the field exist in the core of l10n_fr. (REf : https://github.com/OCA/OpenUpgrade/pull/1532/files#diff-f2654189ad510f78ac03d6927277aebcR2)

So, we should populate siren & NIC when installing this module I guess, and maybe make a warning log with incorrect datas.

What do you think ? 

CC authors : @alexis-via, @fmdl.

**Comment by alexis-via** [comment]
I made a postinstall script in PR https://github.com/OCA/l10n-france/pull/317
