### ISSUE TITLE
[14.0] adding l10n_fr_city module

### ISSUE THREAD

**Issue by petrus-v** [OCA/l10n-france#259]
Hi there ! quite a long time I haven't contribute to OCA, I'm back to maintain some odoo projects !

I would like to purpose a new module l10n_fr_city based on `base_address_city` module 
that would periodically sync data from [La Poste](https://datanova.legroupe.laposte.fr/explore/dataset/laposte_hexasmal/information/)

So installing this module would mark enforce_cities on `res.company` to `True` for Frane

I expect to definie a cron job once a month (this dataset is bi-annual) and
I hope to be able to easly detect new dataset to only compute if needs.
The whole dataset is about 16Mo in json format.

I'll probably use the csv file format if possible with the odoo import system
to using the external id mechanism to keep in sync records.

I'd like to keep information from La Poste to let other developer be able
to use it so I suggest the following mapping:

| res_city field name | La poste field name | Description |
| ------------------- | ------------------- | ----------- |
| insee | code_commune_insee | City identity code |
| zipcode | code_postal | Existing zip code field |
| name | libelle_d_acheminement | The name field. Label used to deliver postal card |
| city_name | nom_de_la_commune | City name (I supposed the one from INSEE database) |
| name1 | ligne_5 | Specification of the associated locality or the name of the associated delegated municipality |
| latitude | coordonnees_gps[0] | GPS coordinate latitude |
| longitude | coordonnees_gps[1] | GPS coordinate longitude |

Is it the right repo to address this module ?
Is there already such effort ?
Do you have better naming field to suggest ?
I'm wondering what's the best field to manager GPS coordinate  ? I would like to
avoid that this modul depends from postGIS postgresql plugin.

Any reactions are welcome
I expect to develop that by the beginning of 2021.

I'll renew my OCA cotisation in the mean time ;)

**Comment by legalsylvain** [comment]
Hi @petrus-v ! Nice to see you again around here! 

> Is it the right repo to address this module ?

well for the specific french part, yes. but maybe we could imagine 2 modules. ``base_city`` and ``l10n_fr_city`` for the specific things. (specific fields, sync with Laposte...)
But, i didn't found where is the module ``base_address_city``, so maybe my remark is not relevant. 

> Is there already such effort ?

I don't know. CC : @alexis-via, @sebastienbeau 

> Do you have better naming field to suggest ?

LGTM.

> I'm wondering what's the best field to manager GPS coordinate ?

Here is current implementation for ``res.partner``. [see](https://github.com/OCA/geospatial/blob/13.0/geoengine_partner/models/partner.py#L12). 

>  I would like to avoid that this modul depends from postGIS postgresql plugin.

Why ? I see it quite mandatory, to handle correctly that field ? 

I think that you could take a look on https://github.com/OCA/geospatial and talk with CampToCamp team that has expertise on this topic. CC : @gurneyalex, @jgrandguillaume ?

**Comment by alexis-via** [comment]
@petrus-v Hello, glad to see you here.
As you don't seem to be aware of all the work that has been done on this topic these last years, please have a look at:
- the discussion on base_location for v14 PR: https://github.com/OCA/partner-contact/pull/1003
- the module base_location_geonames_import: https://github.com/OCA/partner-contact/pull/1024
- my alternative module (developped yesterday and today !) base_address_city_geonames_import: https://github.com/akretion/geonames-import-simple that I would recommend
- the module l10n_fr_base_location_geonames_import https://github.com/OCA/l10n-france/tree/10.0/l10n_fr_base_location_geonames_import (the equivalent features is now embedded inside base_address_city_geonames_import)

And then, once you had a look at this, let's continue the conversation.
I think the main thing to talk about is: is La Poste [1] a better datasource that Geonames [2] ?
I don't have any opinion so far. But we've been using Geonames since v8 in production and it works well.

[1] https://datanova.legroupe.laposte.fr/explore/dataset/laposte_hexasmal/information/?disjunctive.code_commune_insee&disjunctive.nom_de_la_commune&disjunctive.code_postal&disjunctive.ligne_5 a 
[2] https://download.geonames.org/export/zip/

**Comment by ivantodorovich** [comment]
I've also been using geonames import and it's great. Not only in france, but in other countries as well.

**Comment by petrus-v** [comment]
Thanks a lot for all your insights, I'll definitively have a look

@legalsylvain [base_address_city is an OCB module](https://github.com/OCA/OCB/tree/14.0/addons/base_address_city) !

@alexis-via indeed I missed the partner-contact repo ! it looks to do the job already :)

I don't know about data quality, probably `ligne_5` gives a bit more information while cities are grouped together and I was expecting the `recordid` field in json format to be persistent that could be use as external id to ensure data consistency (but not sure it's properly managed as I expect)

@ivantodorovich thanks for your feed back

I'll close this issue and try geonames import ;) !

thanks to your reactivity
