### ISSUE TITLE
account_balance_ebp_csv_export depends on report_aeroo

### ISSUE THREAD

**Issue by gurneyalex** [OCA/l10n-france#59]
Do we really need report_aeroo to generate CSV?

**Comment by alexis-via** [comment]
We definitely need a TXT/CSV report module (would be named "report_txt" for example), but I don't know any. The only reporting engine able to generate text that I know is report_aeroo, that's why I used it.

**Comment by alexis-via** [comment]
@gurneyalex Do you know an existing odoo module that can handle text templates (apart from report_aeroo) ?

**Comment by lepistone** [comment]
@alexis-via I don't know about a reporting engine generating CSVs.

On the other hand, when I had to generate CSVs I just used a text template system (like jinja2 or mako) and then an odoo wizard that allows to download the generated file (like when you download a translation `.po` file from the web interface.

To you think that would be reasonable?

**Comment by alexis-via** [comment]
@lepistone Why not, it that's not too many lines of code. If the number of lines of code is signifiant, then developing a report_txt would be the best option I think. Do you have an example of a module that works like this ? Any pointer to some sample code would be welcomed. I used report_aeroo in the module account_balance_ebp_csv_export only because I was able to generate this TXT report with 0 lines of code and it's the only solution I knew so far.

BTW, do you think it would be better to use jinja2 or mako (or genshi) for such a use-case ?

**Comment by alexis-via** [comment]
@lepistone Note that this module adds a button on the object "trial.balance.webkit" which is ALREADY a wizard, so your suggestion to take as an example the wizard that allows to download the generated files is not good ("trial.balance.webkit" is not a 2-step wizard with a hidden "state" field AFAIK).

**Comment by alexis-via** [comment]
Done with the merge of Sebastien's branch in v8.
